services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=kastanjelaan.vandersmagt.net
      - PASSWORD_HASH=$$2y$$12$$PNsepUKoVauksZ64bIWiPeadl6A/jNPIlF.Ob7nicmDl/XjsYbB8y
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.10.0.x
      - WG_DEFAULT_DNS=192.168.178.1
      - WG_ALLOWED_IPS=192.168.178.0/24, 10.0.0.0/24, 0.0.0.0/0
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"      # Maximum 10MB per log file
        max-file: "2"        # Keep only 2 log files (20MB total)